term.clear()
term.setCursorPos(1,1)
printError("WARNING: ALL ACTIONS WILL BE IRREVERSABLE!")
print("DO YOU WANT TO DELETE ALL FILES?")
print("Press any key to begin reset")
os.pullEvent("key")
fs.delete("/*")
print("Wipe Complete.")
print("The access denied message was just it trying to delete ROM.")
